### ISSUE TITLE
Create Dockerfile for a development build of esmero-php-fpm with Xdebug

### ISSUE THREAD

**Issue by marlo-longley** [esmero/archipelago-docker-images#3]
## Why?

Why didn't I keep it in the same Dockerfile and use conditional, or similar. Why another file. Well I think this is easiest if we want to move it to Docker Hub and also least problems, arguments, for users who don't even want to know about this. Keeps the main Dockerfile the same.

**Comment by DiegoPino** [comment]
@marlo-longley tiny pointer, pulls should start better with a # What. Feels like a # Why is more suited for an issue.

**Comment by DiegoPino** [comment]
Solved via #4. Thanks!
