### ISSUE TITLE
staticfloat/nginx-certbot issue with bind-mount, renewal and active development?

### ISSUE THREAD

**Issue by g7morris** [esmero/archipelago-docker-images#41]
Hello friends, 

Just reporting we've had some super strange behavior lately with the `esmero-web / web` docker [image](https://hub.docker.com/r/staticfloat/nginx-certbot/).

Not sure if it is the age of the image itself?

* https://github.com/staticfloat/docker-nginx-certbot-old & https://hub.docker.com/r/staticfloat/nginx-certbot/ seem to indicate this image is no longer in active development and has been archived. 

Confusingly the same developer has this? https://github.com/staticfloat/docker-nginx-certbot-1 

That looks new? 

Perhaps we should consider moving or testing to that?

---

### Fast Facts / History

Summation: Issue is that the `esmero-web` container can't write to the appropriate directories for ssl cert renewal despite having the correct directory permissions. we checked other working Archi projects to be sure. They however are newer and have not had ssl renewals yet (ages are less than 90 days)

* We had a container that had been running since March that refused to update the certs when simply restarting the containers
* the `esmero-web` container started crashing every 15 seconds because the certs had expired
* all certbot commands to renew said certificate indicated that the process had succeeded but in actuality the certs hadn't been renewed since Feb / March. 
* manually removing contents of these bind mounted directories and restarting the containers did fix the renewal issue **BUT** new ssl certificates were not written to these directories. They were on the container but not written to the server via the bind mounts. 
  * `data_storage/letsencrypt/renewal`
  * `data_storage/letsencrypt/archive`
  * `data_storage/letsencrypt/live`

Our "fix" was to then copy the `letsencrypt` directory from the container to the server and then the contents to the bind mounts
* `docker cp esmero-web:/etc/letsencrypt /home/archi/letsencrypt_backup/letsencrypt`
* `cd /opt/archi-project-live`
* `docker-compose down`
* `cp -rv /home/archi/letsencrypt_backup/letsencrypt/live/* /opt/archi-project-live/data_storage/letsencrypt/live/`
* `cp -rv /home/archi/ssl_archive/letsencrypt/archive/* /opt/archi-project-live/data_storage/letsencrypt/archive/`
* `cp -rv /home/archi/ssl_archive/letsencrypt/renewal/* /opt/archi-project-live/data_storage/letsencrypt/renewal/`
* `docker-compose down`
* `docker-compose up -d`

This seems super strange and tedious to perform every time no? ;)

----

Docker-compose service definition

```bash
version: '3.5'
services:
  web:
    container_name: esmero-web
    image: staticfloat/nginx-certbot
    restart: always
    environment:
      CERTBOT_EMAIL: ${ARCHIPELAGO_EMAIL}
      ENVSUBST_VARS: FQDN
      FQDN: ${ARCHIPELAGO_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${ARCHIPELAGO_ROOT}/config_storage/nginxconfig/conf.d:/etc/nginx/user.conf.d
      - ${ARCHIPELAGO_ROOT}/config_storage/nginxconfig/certbot_extra_domains:/etc/nginx/certbot/extra_domains:ro
      - ${ARCHIPELAGO_ROOT}/drupal:/var/www/html:cached
      - ${DATA_STORAGE}/ngnixcache:/var/cache/nginx
      - ${DATA_STORAGE}/letsencrypt:/etc/letsencrypt
    depends_on:
      - solr
      - php
      - db
    tty: true
    networks:
      host-net: {}
      esmero-net:
        aliases:
          - "${ARCHIPELAGO_DOMAIN}"
```

**Comment by DiegoPino** [comment]
@g7morris odd and strange.

When you say the correct permissions and since these folders (in the bind mount) are created by the [container itself and not by us](https://github.com/esmero/archipelago-deployment-live/tree/1.0.0-RC3/config_storage), can you share what you have there?
Our latest self renewal for that image happened on June 16th 2022, most of the ones we have were renewed automatically early June and no docker pull has been made on those. 

Here are the standard permissions
drwxr-xr-x  9 ec2-user       ec2-user  108 Jul 12 14:26 letsencrypt

and here is a renewal

![image](https://user-images.githubusercontent.com/6946023/179547396-60cb4fcd-0501-44e2-9023-f7e7f77c6e34.png)

I have not update manually anything here, it is a standard `archipelago-deployment-live` deployment. What OS? What are the general permissions of the archipelago-deployment-live folder?

Would love to be able to replicate this. If this can be replicated we can of course move to
https://github.com/esmero/archipelago-deployment-live/blob/1.0.0-RC3/deploy/ec2-docker/docker-compose-aws-s3-arm64.yml
Since that container is being updated and works both on arm64/amd64 but please if possible follow up because I can not seem to replicate this.

**Comment by g7morris** [comment]
Hi @DiegoPino 

Agreed, odd and strange. Thanks for taking a look. 

* OS is Ubuntu Server 22.04 LTS

* Perms of `archipelago-deployment-live` folder are
 ```bash
drwxrwxr-x  9 archi archi 4096 Jul 18 13:09 archipelago-deployment-live
```
We use an `archi` user that would be the same as `ubuntu` or `ec2-user` with sudo perms etc. 

* Perms of contents

```bash
archi@ip-172-21-139-17:/opt/amh-acdc-archi$ ll
total 164
drwxrwxr-x  9 archi archi  4096 Jul 18 13:09 ./
drwxr-xr-x  5 root  root   4096 Mar 17 18:16 ../
-rw-rw-r--  1 archi archi   903 May  5 13:47 .env
drwxrwxr-x  8 archi archi  4096 Jul 15 18:27 .git/
-rw-rw-r--  1 archi archi   746 May 11 13:23 .gitignore
-rw-rw-r--  1 archi archi  9431 Apr 18 14:58 .gitlab-ci.yml
-rw-rw-r--  1 archi archi  1744 Mar 17 18:16 Dockerfile.gulp
drwxrwxr-x  2 archi archi  4096 Mar 17 18:16 Jobs/
-rw-rw-r--  1 archi archi 35149 Mar 17 18:16 LICENSE
-rw-rw-r--  1 archi archi 23164 May  5 13:37 Makefile
-rw-rw-r--  1 archi archi  1192 Mar 17 18:16 README.local.md
-rw-rw-r--  1 archi archi 16676 Apr 18 14:58 README.md
-rw-rw-r--  1 archi archi  4440 Apr 18 14:58 README.remote.md
drwxrwxr-x  9 archi archi  4096 Mar 17 18:16 config_storage/
drwxrwxr-x 11 archi archi  4096 Jul 15 18:27 data_storage/
drwxrwxr-x  5 archi archi  4096 Mar 17 18:16 deploy/
-rw-rw-r--  1 archi archi  4310 May  5 13:37 docker-compose.yml
drwxrwxr-x  2 archi archi  4096 Apr 18 14:58 docs/
drwxrwxr-x 13    82 archi  4096 Jul 15 18:27 drupal/
-rw-rw-r--  1 archi archi   958 May  5 13:37 make.env
```
```bash
/opt/archipelago-deployment-live/data_storage

drwxrwxr-x 11 archi archi     4096 Jul 15 18:27 ./
drwxrwxr-x  9 archi archi     4096 Jul 18 13:09 ../
drwxrwxr-x  2 archi archi     4096 Mar 17 18:16 db/
drwxrwxr-x  2 archi archi     4096 Apr 18 14:58 drupal/
-rw-r--r--  1 archi archi 67260919 Jul 15 18:27 dump.sql
drwxrwxr-x  2 archi archi     4096 Mar 17 18:16 iiiftmp/
drwxr-xr-x  9 root  root      4096 Apr 18 14:58 letsencrypt/
drwxrwxr-x  2 archi archi     4096 Mar 17 18:16 nginxcache/
drwxr-xr-x  7 root  root      4096 Mar 17 18:26 ngnixcache/
drwxrwxr-x  4 archi archi     4096 Mar 17 18:16 selfcert/
drwxrwxr-x  2 archi archi     4096 Mar 17 18:16 solrcore/
drwxrwxr-x  2 archi archi     4096 Mar 17 18:16 solrlib/
```

```bash
/opt/archipelago-deployment-live/data_storage/letsencrypt

drwxr-xr-x  9 root  root  4096 Apr 18 14:58 ./
drwxrwxr-x 11 archi archi 4096 Jul 15 18:27 ../
drwx------  3 root  root  4096 Mar 17 18:26 accounts/
drwx------  3 root  root  4096 Jul 18 14:41 archive/
drwxr-xr-x  2 root  root  4096 Mar 21 18:45 csr/
drwx------  2 root  root  4096 Mar 21 18:45 keys/
drwx------  4 root  root  4096 Jul 18 14:40 live/
drwxr-xr-x  2 root  root  4096 Jul 18 14:41 renewal/
drwxr-xr-x  5 root  root  4096 Mar 17 18:26 renewal-hooks/
````

**Comment by g7morris** [comment]
Woah I have no idea how

```bash
drwxrwxr-x  2 archi archi     4096 Mar 17 18:16 nginxcache/
drwxr-xr-x  7 root  root      4096 Mar 17 18:26 ngnixcache/
```
is possible

**Comment by g7morris** [comment]
@DiegoPino Okay I really appreciate this. Turns out we have a rogue Makefile causing havoc here, updating perms in the wrong way. We'll go hunt that down and update again. 

I think we can close here are 100% user error.
